metadata:
  labels:
    app: ${spring.application.name}
    commit: ${git.commit.id.describe}
  name: ${spring.application.name}
spec:
  replicas: ${deployment.replicas}
  selector:
    matchLabels:
      app: ${spring.application.name}
  template:
    metadata:
      labels:
        app: ${spring.application.name}
        commit: ${git.commit.id.describe}
      annotations:
        timestamp: ${timestamp}
    spec:
      serviceAccountName: todos
      containers:
        - name: ${spring.application.name}
          image: "netshoes/${project.artifactId}:${git.commit.id.describe}"
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: "-Xmx128m"
            - name: SPRING_APPLICATION_NAME
              value: ${spring.application.name}
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${spring.application.name}
                  key: spring.redis.password