apiVersion: v1
kind: ServiceAccount
metadata:
  name: todos
  namespace: todos
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: todos-role
  namespace: todos
rules:
  - apiGroups:
      - ""
    resources:
      ["*"]
    verbs:
      ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: todos-role-binding
  namespace: todos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: todos-role
subjects:
  - kind: ServiceAccount
    name: todos
    namespace: todos